name: Build and Deploy

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # Backend
    - name: Install dependencies (Backend)
      run: |
        cd backend
        npm install

    - name: Build project (Backend)
      run: |
        cd backend
        npm run build

    - name: Deploy Backend to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: tavilgame-backend
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_Backend }}
        package: './backend/dist'  

    # Frontend
    - name: Install dependencies (Frontend)
      run: |
        cd frontend
        npm install

    - name: Build project (Frontend)
      run: |
        cd frontend
        npm run build

    - name: Deploy Frontend to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: tavilgame-frontend
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_Frontend }}
        package: './frontend/build'
