name: Build and Deploy

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies (Backend)
      run: |
        cd backend
        npm install

    - name: Install dependencies (Frontend)
      run: |
        cd frontend
        npm install

    - name: Build project (Backend)
      run: |
        cd backend
        npm run build

    - name: Build project (Frontend)
      run: |
        cd frontend
        npm run build

    - name: Prepare Deployment Directory
      run: |
        mkdir -p deploy_output/backend deploy_output/frontend
        cp -r backend/* deploy_output/backend
        cp -r frontend/* deploy_output/frontend

    - name: Create web.config
      run: |
        echo '<configuration>' >> deploy_output/web.config
        echo '    <system.webServer>' >> deploy_output/web.config
        echo '        <rewrite>' >> deploy_output/web.config
        echo '            <rules>' >> deploy_output/web.config
        echo '                <!-- Rule to route all backend requests -->' >> deploy_output/web.config
        echo '                <rule name="Backend" stopProcessing="true">' >> deploy_output/web.config
        echo '                    <match url="^backend/(.*)" />' >> deploy_output/web.config
        echo '                    <action type="Rewrite" url="backend/dist/{R:1}" />' >> deploy_output/web.config
        echo '                </rule>' >> deploy_output/web.config
        echo '                <!-- Rule to route all other requests to frontend -->' >> deploy_output/web.config
        echo '                <rule name="Frontend" stopProcessing="true">' >> deploy_output/web.config
        echo '                    <match url=".*" />' >> deploy_output/web.config
        echo '                    <action type="Rewrite" url="frontend/{R:0}" />' >> deploy_output/web.config
        echo '                </rule>' >> deploy_output/web.config
        echo '            </rules>' >> deploy_output/web.config
        echo '        </rewrite>' >> deploy_output/web.config
        echo '    </system.webServer>' >> deploy_output/web.config
        echo '</configuration>' >> deploy_output/web.config

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: tavilgame
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4018ECCFB52A4751BF1D3DD939248084 }}
        package: './deploy_output'
