name: Build and Deploy

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies (Backend)
      run: |
        cd backend
        npm install

    - name: Install dependencies (Frontend)
      run: |
        cd frontend
        npm install

    - name: Build project (Backend)
      run: |
        cd backend
        npm run build

    - name: Build project (Frontend)
      run: |
        cd frontend
        npm run build

    - name: Prepare Deployment Directory
      run: |
        mkdir -p deploy_output/backend deploy_output/frontend
        cp -r backend/dist/* deploy_output/backend
        cp -r frontend/.next/* deploy_output/frontend

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: tavilgame
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4018ECCFB52A4751BF1D3DD939248084 }}
        package: './deploy_output'