name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Build and deploy frontend
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build

      - run: zip -r -X frontend.zip node_modules/ .next/ public/ package.json package-lock.json 
        working-directory: frontend
          
      - name: Deploy frontend to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: Tavil 
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_FRONTEND }}
          package: frontend/frontend.zip

      # Build and deploy backend
      - name: Build backend
        run: |
          cd backend
          npm install
          npm run build

      - run: zip -r -X backend.zip node_modules/ dist/ package.json package-lock.json
        working-directory: backend
          
      - name: Deploy backend to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: tavil-backend
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: backend/backend.zip
