name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Build and deploy backend
      - name: Build backend
        run: |
          cd backend
          npm install
          npm run build
          
      - name: Deploy backend to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: tavilgamebackend
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_932711221715456589443288068BB65A }}
          package: backend
